version: '3'

services:
  birthday_notificator_db:
    image: postgres:16.0-alpine3.18
    container_name: bn-db
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
#    volumes:
#      - order:/var/lib/postgresql/data