spring:
  application:
    name: Birthday notificator
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
    password: ${POSTGRES_USERNAME}
    username: ${POSTGRES_PASSWORD}
