spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Birthday notificator
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
    password: ${POSTGRES_USERNAME}
    username: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: none
#    show-sql: true
  flyway:
    schemas:
      - public

telegram:
  bot:
    name: Birthday Notificator
    token: ${TELEGRAM_BOT_TOKEN}
    connection:
      host: http://192.168.205.80:8080 #не работает с localhost
